---
- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: snapd update
  shell: snap install core; snap refresh core
  changed_when: true
  failed_when: false

- name: snapd socket
  systemd:
    name: snapd.socket
    enabled: true    
