---
logstash_version: '7.x'

logstash_package: logstash

logstash_listen_port_beats: 5044

logstash_elasticsearch_hosts:
  - http://localhost:9200

logstash_local_syslog_path: /var/log/syslog
logstash_monitor_local_syslog: true

logstash_local_auth_log_path: /var/log/auth.log

logstash_local_nginx_log_path: "/var/log/nginx/*access.log"

logstash_heap_size_min: 1g
logstash_heap_size_max: 1g

logstash_dir: /usr/share/logstash

logstash_ssl_dir: /etc/pki/logstash
logstash_ssl_certificate_file: ""
logstash_ssl_key_file: ""

logstash_enabled_on_boot: true

logstash_install_plugins:
  - logstash-input-beats
  - logstash-input-http
  - logstash-filter-multiline

logstash_setup_default_config: true
