terraform {
  required_providers {
    vsphere = {
      source  = "hashicorp/vsphere"
      version = ">= 2.6.1"
    }
  }
  required_version = ">= 1.7.1"
}

provider "vsphere" {
  vsphere_server       = var.vsphere_server
  user                 = var.vsphere_username
  password             = var.vsphere_password
  allow_unverified_ssl = var.vsphere_insecure
}

variable "builds" {
  type = list(
    object(
      {
        name=string,
        builder_type=string,        
        artifact_id=string,
        packer_run_uuid=string,
        custom_data=object({
          build_username=string,
          build_password=string 
        }) 
      }
    )
  )
  description = "List of images, as generated by Packer's 'Manifest' post-processor."
}
variable "last_run_uuid" {
  type = string
}

locals {
  build_by           = "Built by: ${var.vsphere_username} with HashiCorp Terraform"
  build_date         = formatdate("YYYY-MM-DD hh:mm ZZZ", timestamp())  
  build_from         = "Built from: ${var.vsphere_template != null ? var.vsphere_template : split(":", element(var.builds, 0).artifact_id)[0]}"
  build_description  = "Built on: ${local.build_date}\n${local.build_by}\n${local.build_from}"
  ansible_user       = "${split(":", element(var.builds, 0).custom_data.build_username)[0]}"
  ansible_password   = "${split(":", element(var.builds, 0).custom_data.build_password)[0]}"
}
