Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2004"
    config.ssh.forward_agent = true
    config.vm.provider :libvirt do |domain|
     domain.memory = 1024
     domain.cpus = 1
    end
    config.vm.network "forwarded_port", guest: 80, host: 8080
    
    config.vm.provision "install_graylog", type:'ansible' do |ansible|
      ansible.playbook = "install_graylog.yaml"
      ansible.limit = "all"
      ansible.extra_vars = {
        # You can add any extra variables here if required by your Ansible playbook
      }
    end

    config.vm.provision "install_nginx", type:'ansible' do |ansible|
      ansible.playbook = "install_nginx.yaml"
      ansible.limit = "all"
      ansible.extra_vars = {
        # You can add any extra variables here if required by your Ansible playbook
      }
    end
end
  