---
- name: start nginx
  service:
    name: nginx
    state: started
    enabled: true  

- name: reload nginx
  command: /usr/sbin/nginx -s reload

- name: restart nginx
  service:
    name: nginx
    state: restarted
