---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Create vhost directory
  file:
    path: "/var/www/{{ item.server_name }}"
    state: directory
    mode: "0775"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
  with_items: "{{ nginx_vhosts }}"
  
- name: Copy site index
  template:
    src: index.html.j2
    dest: "/var/www/{{ item.server_name }}/index.html"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: '0644'
  with_items: "{{ nginx_vhosts }}"

- name: Copy site files
  copy:
    src: files/
    dest: "/var/www/{{ item.server_name }}/"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: '0644'
  with_items: "{{ nginx_vhosts }}"  
  
- name: Copy vhost configuration
  template:
    src: vhost.conf.j2
    dest: "{{ nginx_vhost_path }}/{{ item.server_name }}.conf"
    owner: root
    group: "{{ nginx_group }}"
    mode: '0644'
  with_items:
    - "{{ nginx_vhosts }}"
  notify: reload nginx