---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags: vhost_conf

- name: Check if vhost directory already exists
  stat: 
    path: "/var/www/{{ item.server_name }}"
  with_items: "{{ nginx_vhosts }}"
  register: vhost_dir
  tags: vhost_conf

- name: Check if vhost config already exists
  stat: 
    path: "{{ nginx_vhost_path }}/{{ item.server_name }}.conf"
  with_items: "{{ nginx_vhosts }}"
  register: vhost_conf
  tags: vhost_conf

- name: Create vhost directory
  file:
    path: "{{ item.item.root }}"
    state: directory
    mode: "0775"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
  with_items: "{{ vhost_dir.results }}"
  when: not item.stat.exists
  tags: vhost_conf

  
- name: Copy site index
  template:
    src: index.html.j2
    dest: "{{ item.item.root }}/index.html"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: '0644'
  with_items: "{{ vhost_dir.results }}"
  when: not item.stat.exists
  tags: vhost_conf

- name: Copy site files
  copy:
    src: files/
    dest: "{{ item.item.root }}/"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: '0644'
  with_items: "{{ vhost_dir.results }}"
  when: not item.stat.exists
  tags: vhost_conf
  
- name: Copy vhost configuration
  template:
    src: vhost.conf.j2
    dest: "{{ nginx_vhost_path }}/{{ item.item.server_name }}.conf"
    owner: root
    group: "{{ nginx_group }}"
    mode: '0644'
    backup: true
  with_items: "{{ vhost_conf.results }}"
  changed_when: true  
  notify: reload nginx
  when: not item.stat.exists
  tags: vhost_conf