---
nginx_vhosts:
  - listen: "80"
    server_name: "{{ ansible_fqdn }}"
    root: "/var/www/{{ ansible_fqdn }}"
    locations_config:
      - path: '/'
        config: |-
          proxy_pass http://127.0.0.1:9000;
          proxy_redirect off;
          proxy_buffering off;

          proxy_http_version 1.1;
          proxy_set_header Connection "Keep-Alive";
          proxy_set_header Proxy-Connection "Keep-Alive";

          



