---
nginx_vhosts:
  - listen: "80"
    server_name: "{{ inventory_hostname }}"
    root: "/var/www/{{ inventory_hostname }}"
    access_log_config:
      - format: logstash
        path: "/var/log/nginx/{{ inventory_hostname }}_access.log"
        options: ''
    locations_config:
      - path: '/'
        config: |-
          proxy_pass http://127.0.0.1:5601;
          proxy_redirect off;
          proxy_buffering off;

          proxy_http_version 1.1;
          proxy_set_header Connection "Keep-Alive";
          proxy_set_header Proxy-Connection "Keep-Alive";

          auth_basic           "Nginx with basic auth.";
          auth_basic_user_file /etc/nginx/passwdfile;    



